name: DepthGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile=0.8.1
  - python=3.9.13
  - pip=22.3.1
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - pytorch3d=0.7.5
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization-depth-acc
    - submodules/simple-knn
